# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    OfferTwigExt:
        class: AppBundle\Twig\Offer
        public: false
        arguments: [@Offer]
        tags:
            - { name: twig.extension }
    Brand:
        class: AppBundle\Services\Brand
        calls:
            - [setContainer,[ @service_container ] ]
            - [setRequest, [@request_stack]]
    Offer:
        class: AppBundle\Services\Offer
        calls:
            - [setContainer,[ @service_container ] ]
            - [setTokenStorage,[ @security.token_storage ] ]
            - [setRouter,[ @router ] ]
            - [setDoctrine,[ @doctrine ] ]
            - [setMaxMindDB,[ %kernel.root_dir%/../src/AppBundle/MaxMindDB/GeoLite2-City.mmdb ] ]
# Brands!
    PlatformFactory:
        class: AppBundle\Services\Platform\PlatformFactory
        calls:
            - [setContainer,[ @service_container ] ]
    Spot:
        class: AppBundle\Services\Platform\Spot
        calls:
            - [setDoctrine,[ @doctrine ] ]
            - [setValidator,[ @validator ] ]