# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    OfferTwigExt:
        class: AppBundle\Twig\Offer
        public: false
        arguments: [@Offer]
        tags:
            - { name: twig.extension }
    app.user_manager:
        class: AppBundle\UserBundle\Doctrine\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, @Brand, AppBundle\Entity\User]
    fos_user.registration_listener:
        class: AppBundle\EventListener\FOSRegistrationListener
        arguments: [@doctrine]
        tags:
            - { name: kernel.event_subscriber }
    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }
    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
    Brand:
        class: AppBundle\Services\Brand
        calls:
            - [setContainer,[ @service_container ] ]
            - [setRequest, [@request_stack]]
    Offer:
        class: AppBundle\Services\Offer
        calls:
            - [setContainer,[ @service_container ] ]
            - [setTokenStorage,[ @security.token_storage ] ]
            - [setRouter,[ @router ] ]
            - [setDoctrine,[ @doctrine ] ]
            - [setMaxMindDB,[ %kernel.root_dir%/../src/AppBundle/MaxMindDB/GeoLite2-City.mmdb ] ]
# Brands!
    PlatformFactory:
        class: AppBundle\Services\Platform\PlatformFactory
        calls:
            - [setContainer,[ @service_container ] ]
    Spot:
        class: AppBundle\Services\Platform\Spot\Spot
        calls:
            - [setDoctrine,[ @doctrine ] ]
            - [setValidator,[ @validator ] ]
            - [setUserManager,[ @fos_user.user_manager ] ]